name: portfolio
description: "A Flutter web app showcasing how to build a responsive portfolio website for various screen sizes and operating systems. This project features animations and a sleek design, highlighting Flutter's capabilities in creating versatile and visually appealing web applications."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2



  # state management
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5

  #Connections
  dio: ^5.4.3+1
  connectivity_plus: ^6.0.3

  #UI
  fluttericon: ^2.0.0
  fluttertoast: ^8.2.5
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  rive: ^0.13.5
  scrollable_positioned_list: ^0.3.8

  #Tools
  intl: ^0.19.0



  #Test
  bloc_test: ^9.1.7
  mockito: ^5.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/locales/
    - assets/images/
    - assets/images/projects/
    - assets/rives/
    - assets/icons/
    - assets/fonts/
    - assets/svgs/

  fonts:
    - family: cairo
      fonts:
        - asset: assets/fonts/cairo/cairo_extra_light.ttf
          weight: 200
        - asset: assets/fonts/cairo/cairo_light.ttf
          weight: 300
        - asset: assets/fonts/cairo/cairo_regular.ttf
          weight: 400
        - asset: assets/fonts/cairo/cairo_medium.ttf
          weight: 500
        - asset: assets/fonts/cairo/cairo_semi_bold.ttf
          weight: 600
        - asset: assets/fonts/cairo/cairo_bold.ttf
          weight: 700
        - asset: assets/fonts/cairo/cairo_extra_bold.ttf
          weight: 800
        - asset: assets/fonts/cairo/cairo_black.ttf
          weight: 900
